o1dstaRs/heroes-of-crypto-client

- game/core/scripts/generate_image_imports.js
- game/core/src/abilities/abilities.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/ai/ai.ts
- game/core/src/draw/drawer.ts
- game/core/src/generated/image_imports.ts
- game/core/src/grid/grid.ts
- game/core/src/grid/grid_math.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/menu/button.ts
- game/core/src/path/path_helper.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- game/core/src/utils/math.ts
- Do not use box2d in common places
- Defined XY in `math` module
- Use distance from `math` instead of `b2Vec2`
- Avoid using `b2Body` in libraries and math code
- Show game version in the UI
> Preparing package before separation into client and common code

- game/core/src/ai/ai.ts
The PR has following changes:
- fix bug in AI for big units, the big unit could not attack some time
- add logging for AI
> fix ai for big units

- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/config_provider.ts
- game/core/src/configuration/abilities.json
- game/core/src/configuration/creatures.json
- game/core/src/configuration/spells.json
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/UnitStatsListItem/index.tsx
- game/core/src/units/units.ts
- Cowardice hower fixes
- Show units range and aura on hover
- Mdef matters on Fire shield and Dragon Fire
- Morale is now a buff, Dismorale is a debuff
- Heavy armor magic multiplication
- UI element border for luck and attack multiplier
- Show proper range damage on hidden target
Also added a new ability "Wardguard" granting 25% magic resist.
> Bugfixes and improvements

- game/core/src/abilities/blindness_ability.ts
- game/core/src/abilities/boar_saliva_ability.ts
- game/core/src/abilities/spit_ball_ability.ts
- game/core/src/abilities/stun_ability.ts
- game/core/src/ai/ai.ts
- game/core/src/configuration/abilities.json
- game/core/src/configuration/creatures.json
- game/core/src/configuration/spells.json
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/spells/spells_helper.ts
- game/core/src/ui/UnitStatsListItem/index.tsx
- game/core/src/units/units.ts
- game/core/src/utils/strings.ts
- Fix morale related bugs
- Fix trajectory bug when large unit attacks small one with the same x or y coord
- Evaluate range attack w/o box2d
- "Magic Mirror" spell functionality
- Large Caliber ability placeholder
> Range attack changes and more

- .stylelintrc.json
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/large_caliber_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/one_in_the_field_ability.ts
- game/core/src/configuration/abilities.json
- game/core/src/configuration/creatures.json
- game/core/src/configuration/spells.json
- game/core/src/handlers/attack_handler.ts
- game/core/src/handlers/move_handler.ts
- game/core/src/manager.ts
- game/core/src/path/path_helper.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/spells/spells.ts
- game/core/src/state/fight_state_manager.ts
- game/core/src/state/visible_state.ts
- game/core/src/statics.ts
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/Section/style.scss
- game/core/src/ui/UnitStatsListItem/index.tsx
- game/core/src/ui/controls/Radio/style.scss
- game/core/src/ui/style.scss
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- package.json
- scripts/copy_hoc_common.sh
- scripts/pull_hoc_common.sh
- yarn.lock
- Moved out FightState
- New spell: Courage
- Removed Totem of Courage from the game
> Move out FightState to Common code

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/lucky_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
New abilities added
- Sky Runner
- Through Shot
- Unyielding Power
- Lucky Strike
> New abilities added

- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/rapid_charge_ability.ts
- game/core/src/abilities/shatter_armor_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/UnitStatsListItem/index.tsx
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- New abilities added: Shatter Armor, Rapid Charge and Wolf Trail Aura
> New abilities added: Shatter Armor, Rapid Charge and Wolf Trail Aura

- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/penetrating_bite_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/spells/spells_helper.ts
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- Added Valkyrie, Hyena and Mantis
> Added Valkyrie, Hyena and Mantis

- game/core/src/abilities/deep_wounds_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/units/units.ts
- Created Deep Wounds abilities
> Created Deep Wounds abilities

- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/draw/drawer.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/DraggableToolbar/index.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- Select map type in Sandbox
- Ability to transder Wild Regeneration
- Fix bug where Tsar Cannon is able to respond to a range attack
> Select map type in Sandbox. Ability to transder Wild Regeneration

- game/core/src/abilities/blindness_ability.ts
- game/core/src/abilities/boar_saliva_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/miner_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/spit_ball_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
- Madness, Blind Fury and Miner abilities
> Madness, Blind Fury and Miner abilities

- game/core/src/abilities/paralysis_ability.ts
- game/core/src/abilities/shatter_armor_ability.ts
- game/core/src/abilities/stun_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
> Mechanism ability added

- game/core/src/ai/ai.ts
- scripts/pull_hoc_common.sh
changes:
- set debug logging for ai through environment variable `DEBUG_AI`, if set to `true` then ai debug logging is enabled
- fix pull common script
> set log to debug via env variable

- game/core/src/ai/ai.ts
fix bug when big units were moving when they should stay and attack
> Fix big units movement checks

- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/RightSideBar/index.tsx
- Button to pick random map type
- Minor bugfixes and improvements
> Minor bugfixes and improvements

- game/core/src/abilities/double_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/state/visible_state.ts
- game/core/src/ui/DamageBubble/index.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/Main/index.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- game/core/src/ui/RightSideBar/UnitInputActions.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/units/units_holder.ts
- Initial augments implementation
- Ability to select particular placemement
> Initial augments implementation. Ability to select particular placemement

- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- game/core/src/ui/RightSideBar/UnitInputActions.tsx
- game/core/src/units/units.ts
- Propagate Armor and Might augments
> Propagate Armor and Might augments

- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- game/core/src/units/units.ts
- Movement, Sniper and Might augments in the Right menu
> Movement, Sniper and Might augments

- game/core/src/handlers/attack_handler.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/state/visible_state.ts
- game/core/src/statics.ts
- game/core/src/ui/DamageBubble/index.tsx
- game/core/src/ui/DraggableToolbar/index.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/units/units.ts
- Connect DraggableToolbar buttons
> Connect DraggableToolbar buttons

- game/core/src/abilities/abilities_helper.ts
- game/core/src/abilities/blindness_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/draw/drawer.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/Popover/index.tsx
- game/core/src/units/units.ts
- Draw range distance, auras and movement cellts pre-fight
> Draw range distance, auras and movement cellts pre-fight

- game/core/src/abilities/chain_lighting_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
- game/core/src/units/units_holder.ts
- Thunderbird unit added
- Chain Lightning and Wind Element abilities
- Tsar Cannon cannot shot through Angel which has "Arrows Wingshield Aura"
> Thunderbird unit added, Chain Lightning and Wind Element abilities

- game/core/src/draw/drawable_square_placement.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/statics.ts
- game/core/src/ui/LeftSideBar/MessageBox.tsx
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/ui/index.tsx
- Adjust bar sizes depending on the window size
- Refresh units information on augmentation
> Adjust bar sizes depending on the window size

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/chain_lighting_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/handlers/move_handler.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/heroes.ts
- game/core/src/units/renderable_unit.ts
- game/core/src/units/units.ts
- game/core/src/units/units_factory.ts
- game/core/src/units/units_holder.ts
- Chain Lightning to affect on Goblin Knight, fix range attacks
- Split Unit into Unit and RenderableUnit
> Split Unit into Unit and RenderableUnit + more

- game/core/src/ai/ai.ts
- game/core/test/ai/ai.test.ts
unstuck flying units, check more cells that the unit can go to
> init unstuck flying units ai changes

- game/core/src/handlers/attack_handler.ts
- Fix harpy's Castling ability
> Fix harpy's Castling ability

- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
- game/core/src/units/units_factory.ts
- game/core/src/units/units_holder.ts
- Champion added and Tie up the Horses Aura
> Champion added and Tie up the Horses Aura

- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/handlers/move_handler.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/DraggableToolbar/index.tsx
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/units/units.ts
- Adjustable Left Side Bar items
- Re-scale everything on zoom or resize action
- Increase posibility of Petrifying Gaze
- Fix hover action when mouse moved outside of the Canvas
> Adjustable left side bar items + more

- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/units.ts
- Close spellbook on Escape button click
> Close spellbook on Escape button click

- README.md
- game/core/src/obstacles/obstacle.ts
- game/core/src/obstacles/obstacle_generator.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/spells/renderable_spell.ts
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/UpNext.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/ui/UpNextOverlay/index.tsx
- game/core/src/ui/index.tsx
- Click ALT to see who is making next turn
> Click ALT to see who is making next turn

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/draw/drawer.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/manager.ts
- game/core/src/obstacles/obstacle.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/spells/renderable_spell.ts
- game/core/src/state/visible_state.ts
- game/core/src/stats/damage_stats.ts
- game/core/src/ui/Popover/index.tsx
- Range units now can destroy the mountain
- Fix Through Shot target near the Block area
- DamageStatisticHolder to store actual damage
> Range units now can destroy the mountain

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/miner_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/ai/ai.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/manager.ts
- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/stats/damage_stats.ts
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/units/units_factory.ts
- game/core/test/ai/ai.test.ts
- Melee units to destroy mountain
- Started on "Made of Fire" ability
> Melee units to destroy mountain. Started on Made of Fire ability

- game/core/package.json
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- yarn.lock
- Ability to cast Resurrection
- Update Axios to `1.7.4`
> Ability to cast Resurrection

- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/renderable_unit.ts
> Disguise Aura added

- game/core/package.json
[Switch version to v0.1.3](https://github.com/o1dstaRs/heroes-of-crypto-client/commit/75af7e66f3418392cb2fb31239c814af9ab3e192)
> Switch version to v0.1.3

- game/core/src/abilities/miner_ability.ts
> Fix Miner ability logging

- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- Use green/red overlays intead of flags in LeftSideBar
- Moved buffs/debuffs section for widescreen layout
> UI improvements

- game/core/src/scenes/scene.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/RightSideBar/FightControlToggler.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- Players to select Synergies from the RightSideBar
- Define Synergies powers
> Continuing on Faction Synergies

- game/core/src/abilities/aggr_ability.ts
- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/blindness_ability.ts
- game/core/src/abilities/boar_saliva_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/deep_wounds_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/lucky_strike_ability.ts
- game/core/src/abilities/miner_ability.ts
- game/core/src/abilities/paralysis_ability.ts
- game/core/src/abilities/pegasus_light_ability.ts
- game/core/src/abilities/penetrating_bite_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/rapid_charge_ability.ts
- game/core/src/abilities/shatter_armor_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/spit_ball_ability.ts
- game/core/src/abilities/stun_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/units/renderable_unit.ts
- Synergy to extend stack abilities power
> Synergy to extend stack abilities power

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/petrifying_gaze_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/state/visible_state.ts
- game/core/src/ui/LeftSideBar/MessageBox.tsx
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/LeftSideBar/UpNext.tsx
- game/core/src/ui/UpNextOverlay/index.tsx
- game/core/src/units/heroes.ts
- game/core/src/units/renderable_unit.ts
- game/core/src/units/units_factory.ts
- Chaos synergies added: MOVEMENT and BREAK_ON_HIT
> Chaos synergies added: MOVEMENT and BREAK_ON_HIT

- game/core/src/abilities/aoe_range_ability.ts
- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/abilities/double_punch_ability.ts
- game/core/src/abilities/double_shot_ability.ts
- game/core/src/abilities/fire_breath_ability.ts
- game/core/src/abilities/fire_shield_ability.ts
- game/core/src/abilities/lightning_spin_ability.ts
- game/core/src/abilities/skewer_strike_ability.ts
- game/core/src/abilities/through_shot_ability.ts
- game/core/src/handlers/attack_handler.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- Nature and Life synergies added
- Refactor the morale computation code and propagation
> Nature and Life synergies added

- game/core/package.json
- game/core/src/manager.ts
- game/core/src/scenes/test_heroes.ts
- game/core/src/state/visible_state.ts
- game/core/src/ui/LeftSideBar/SynergiesRow.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/Popover/index.tsx
- game/core/src/ui/RightSideBar/CalendarInfo.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- game/core/src/ui/RightSideBar/VersionDisplay.tsx
- game/core/src/ui/RightSideBar/index.tsx
- Render Synergies on top left corner
> Render Synergies on top left corner

- game/core/src/scenes/test_heroes.ts
> Updated Summon amount

- game/core/src/ui/LeftSideBar/SynergiesRow.tsx
- game/core/src/ui/LeftSideBar/UnitStatsListItem.tsx
- game/core/src/ui/RightSideBar/SideToggleContainer.tsx
- Morale Synergy to increase luck as well
> Morale Synergy to increase luck as well

- game/core/src/scenes/test_heroes.ts
- package-lock.json
> Fixing the hover bugs

- game/core/src/abilities/chain_lightning_ability.ts
- game/core/src/state/visible_state.ts
- game/core/src/ui/DraggableToolbar/index.tsx
- game/core/src/ui/LeftSideBar/index.tsx
- game/core/src/ui/Main/index.tsx
- game/core/src/ui/RightSideBar/index.tsx
- game/core/src/ui/index.tsx
- Avoid text select/copy/paste while in game
- Optimize rendering related to window re-size or other adjustments
- Draggable toolbar to avoid out-of-window position
- Return back Chain Lightning magic damage if "Magic Mirrow" is enabled on a unit
> Optimize React rendering. Avoid Draggable tool bar with outside of the window position

- package.json
- yarn.lock
> Cross-platform build

- game/core/src/ai/ai.ts
- game/core/test/ai/ai.test.ts
fix stuck flying units, should move as far as they can.
> fix stuck flying units over water

- game/core/src/api/axios.tsx
- game/core/src/ui/PickAndBan/HelpQuestionMark.tsx
- game/core/src/ui/PickAndBan/Timer.tsx
- game/core/src/ui/PickAndBan/index.tsx
- game/core/src/ui/auth/context/auth_provider.tsx
- game/core/src/ui/auth/context/types.ts
- game/core/src/ui/index.tsx
[Continuing on the Pick phase UI](https://github.com/o1dstaRs/heroes-of-crypto-client/commit/be8beb5c763580cd335add6b60a44e7aa61c152e)
> Continuing on the Pick phase UI

- game/core/.env
- game/core/.env.production
- game/core/package.json
- game/core/src/api/axios.tsx
- game/core/src/scenes/test_heroes.ts
- game/core/src/ui/PickAndBan/HelpQuestionMarkIcon.tsx
- game/core/src/ui/PickAndBan/RevealCreatureImageBox.tsx
- game/core/src/ui/PickAndBan/RevealIcon.tsx
- game/core/src/ui/PickAndBan/index.tsx
- game/core/src/ui/auth/context/auth_provider.tsx
- game/core/src/ui/auth/context/types.ts
- game/core/src/ui/index.tsx
- game/core/src/ui/unit_ui_constants.tsx
- Reveals functionality placeholder
- Fix bug where units can be placed into an enemy's placement
> Reveals functionality placeholder & bugfixes
